### ISSUE TITLE
Invoke Regression when Pushing code to Main Branch

### ISSUE THREAD

**Issue by grafflr2** [grafflr/deepnlu#41]
The regression was created in #34  and can be invoked on windows using
```powershell
 .\scripts\Run-Regression.ps1
```
(It should be a trivial exercise to create a shell script equivalent of this simple file).

The regression will iterate through multiple test case definitions expressed in YAML format.

A test case tells the regression suite what input to send to which service and what kind out of output to look for.

The result is an easy-to-read no-code test harness solution

I want this regression to be executed automatically when code is pushed to the main branch in this repository.

The regression must be 100% successful.

Even a single error should result in a notification and a high priority fix requested.

There should be a way to automate this within Git as well as provide a status update to Slack in the event of failure.

**Comment by grafflr2** [comment]
@jtepen are you interested in taking this on?

**Comment by jtepen** [comment]
Sure.  I'll see what I can figure out.

**Comment by jtepen** [comment]
I was able to reproduce the same results as the PowerShell script using the Shell script.  I need to work on mapping the correct directory for anyone to use. 

<img width="936" alt="Screen Shot 2022-06-07 at 9 28 43 PM" src="https://user-images.githubusercontent.com/103457879/172519362-6fcc94da-75c4-4104-b546-b4f32370ce5a.png">

<img width="778" alt="Screen Shot 2022-06-07 at 9 28 22 PM" src="https://user-images.githubusercontent.com/103457879/172519385-a60093b6-beab-4289-ba40-a9d88310e149.png">

**Comment by jtepen** [comment]
Reopened because I missed this requirement:

> There should be a way to automate this within Git as well as provide a status update to Slack in the event of failure.

**Comment by jtepen** [comment]
I set up a Github action that does the following:

1 - Request a container from the Github environment.  
2 - Install python 3.8.5 and poetry.  
3 - Copy the latest deepnlu code from the repo  
4 - Run an updated Make All file. This one will not automatically run the regression test during the build.  
5 - Run the regressions test, but it is using Assert Command Line Output that is looking for "Regression Successful" in the test output.  
6 - A slack message will be sent to the graffl-git channel when the regression test passes or fails.
